

export default {
  title: 'Tracer UI',
  themes: {
    'color-body': '#fff',
    'color-bar': '#fff',
    'color-sub-bar': '#f5f5f5',
    'color-text': '#555',
    'color-sub-text': '#888',
    'color-border': 'rgba(0, 0, 0, 0.12)',
    'color-shadow': '#eee',
    'color-introduce-border': '#2196f3',
    'color-primary': '#41b883',
    'color-link': '#00c48f',
    'color-type': '#00c48f',
    'color-progress': '#1d92e9',
    'color-progress-track': '#fff',
    'color-side-bar': '#3a7afe',
    'color-side-bar-active-background': '#e7f5ee',
    'color-app-bar': '#3a7afe',
    'color-nav-button-hover-background': 'rgba(0, 0, 0, 0.08)',
    'color-pc-language-active': '#3a7afe',
    'color-pc-language-active-background': '#edf5ff',
    'color-code-bg': '#ffffff',
    'color-table-th-bg': '#fafafc',
    'color-table-qoute-bg': '#fff',
  },
  darkThemes: {
    'color-body': '#121212',
    'color-bar': '#1e1e1e',
    'color-sub-bar': '#272727',
    'color-text': 'rgba(255, 255, 255, 0.82)',
    'color-sub-text': '#aaa',
    'color-border': '#333',
    'color-shadow': '#121212',
    'color-introduce-border': '#555',
    'color-primary': '#41b883',
    'color-link': '#10c48f',
    'color-type': '#10c48f',
    'color-progress': '#5580f8',
    'color-progress-track': '#202020',
    'color-side-bar': '#4a7afe',
    'color-side-bar-active-background': '#233633',
    'color-app-bar': '#4a7afe',
    'color-nav-button-hover-background': 'rgba(255, 255, 255, 0.08)',
    'color-pc-language-active': '#4a7afe',
    'color-pc-language-active-background': '#4a7afe20',
    'color-code-bg': '#202020',
    'color-table-th-bg': '#1e1e1e',
    'color-table-qoute-bg': '#18181c',

  },
}